### ISSUE TITLE
[REQUEST] [WCS] support

### ISSUE THREAD

**Issue by BlackYuzia** [Rachnus/Futuristic-Grenades#3]
Hello.
I have some server with installed mod "WCS". (WC:SOURCE)
That mod have some different with SuperHero mod, but he good and interest.

I here,  because I hope edit that plugin from wcs.
I mean, create a ultimates, basic to your mod.

That request for help, if you want, and have time. You can help. If not - you can say: not, or etc.
I understand you, and find other people who can help me.

I do not sale that skills, and not  give only vip/prem/admin. That skills can use anybody.

I see good work, and hope see that create in my server. if you want to pay from your job. I have a few lids, and a cola. will suit? :d

**Comment by BlackYuzia** [comment]
I search a man. Who can help.
I can give you all what you need from edit to wcs mod.

**Comment by Pelipoika** [comment]
Bye!

**Comment by BlackYuzia** [comment]
yea.
